-- Add tenant limit columns - using direct SQL for robustness
ALTER TABLE "Tenant" ADD COLUMN "maxClients" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Tenant" ADD COLUMN "maxInvoices" INTEGER NOT NULL DEFAULT 20;
ALTER TABLE "Tenant" ADD COLUMN "maxLoans" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "Tenant" ADD COLUMN "maxUsers" INTEGER NOT NULL DEFAULT 1;
